// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    
		int N = Integer.parseInt(args[0]);

		int upperHalf = 0;
		int lowerhalf = 0;

		for (int i = 0; i < N; i++) {
			double randomNumber = Math.random();

			if (randomNumber > 0.5) { upperHalf++;
				
			} else lowerhalf++;
		};

		double ratio;

		if (upperHalf > lowerhalf) { ratio = ((double) lowerhalf) / upperHalf;
			
		} else ratio = ((double) upperHalf) / lowerhalf;

		System.out.println(" > 0.5: " + upperHalf + " times");
		System.out.println("<= 0.5: "+ lowerhalf + " times");

		if (upperHalf != 0 && lowerhalf != 0) {System.out.println("Ratio: " + ratio);
			
		}
		
	}
}
